### ISSUE TITLE
Le nom du jeu ?

### ISSUE THREAD

**Issue by Somroti** [Aqu1tain/LoupsGarousCrenin#1]
Le projet GitHub s'appelle "Loup Garou Cerlin", sur le Wiki Loup Garou il s'appelle "Loup Garou Crenin" et sur le dos des cartes il y a marqué "Loup Garou Corentin". Quel est le nom du jeu ?

**Comment by Aqu1tain** [comment]
Aha salut, le nom du jeu est «Loup Garou Crénin»… Ça fait longtemps que j’ai pas mis à jour ce repo… Il faut que je m’en occupe ! Merci pour l’intérêt !

**Comment by nnWhisperer** [comment]
It's a nice version of the game but loup garou does already belong to the Thiercelieux team, doesn't it? Hence opening this game like this may not be possible as it is their universe and the characters etc. Have you seen it with a legal consular?

**Comment by Aqu1tain** [comment]
> It's a nice version of the game but loup garou does already belong to the Thiercelieux team, doesn't it? Hence opening this game like this may not be possible as it is their universe and the characters etc. Have you seen it with a legal consular?
@nnWhisperer 

Quick bit of context: the werewolf party game isn't actually a Thiercelieux creation. Their edition is itself an adaptation of "Mafia", a social deduction game created by Dimitry Davidoff back in 1986, which is in the public domain. The whole village-votes-by-day / hidden-killers-by-night structure comes from there, not from them.

That's why you see so many werewolf games coexisting legally: One Night Ultimate Werewolf, Ultimate Werewolf, Werewolves of Miller's Hollow, tons of digital versions, etc. It's a genre, not a single IP.

This project has its own name, its own illustrations, and is open source and non-commercial, so it fits squarely in that tradition. Appreciate you taking the time to check though!
